version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    restart: always
    ports:
      - '41773:51773'
      - '42773:52773'
      - '43773:53773'
    volumes:
      - ./:/irisdev/app
      - C:/GitHub/:/external
